# Generated by Django 3.0.5 on 2020-04-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_app', '0002_auto_20200417_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
