# Generated by Django 3.0.5 on 2020-04-18 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_app', '0004_auto_20200417_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests',
            field=models.ManyToManyField(related_name='_user_friend_requests_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
