# Generated by Django 3.0.5 on 2020-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_app', '0005_auto_20200418_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='per_image/'),
        ),
    ]
