# Generated by Django 3.0.5 on 2020-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media_app', '0008_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='my group', max_length=100),
            preserve_default=False,
        ),
    ]
