# Generated by Django 3.0.5 on 2020-04-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media_app', '0010_auto_20200422_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppost',
            name='user',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Media_app.Group'),
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
